### ISSUE TITLE
Create anchors for components

### ISSUE THREAD

**Issue by Nighthawk14** [swanky-docs/swanky-core#26]
If we have multiple components, the ability to set an anchor tag for each (creating from component name?) and then have sublinks on the sidebar would be really nice, so we could jump between components.

**Comment by rodleviton** [comment]
@Nighthawk14 I totally agree. This has been considered previously and I think it would be a good option to set globally how sub sections are rendered e.g.

by default subSections are rendered as individual pages. It would be nice to be able to render sub sections on one page with the sub nav being linked to the anchor of each section.

`subSectionDisplayType: anchor | page (default)`

Would love some help with the option name :) @uglow @Nighthawk14 

```
subSectionDisplayType: anchor

sections:
  - title: Foundation
    content: src/content/foundation/*.md

    subSections:
      - title: Colour Palette
        content: src/content/foundation.md

      - title: Typography
        content: src/content/foundation.md

      - title: Grids & Units
        content: src/content/foundation.md
```
